// <auto-generated />
namespace Hnatob.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newLogicResponsibleBetween9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newLogicResponsibleBetween9));
        
        string IMigrationMetadata.Id
        {
            get { return "201903040051092_newLogicResponsibleBetween9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
